In [ ]:
# (2) OrdinalEncoding ------> it is sed when to encode multiple columns

In [1]:
import numpy as np
import pandas as pd

In [ ]:
# df = pd.read_csv('/content/covid_toy - covid_toy.csv')
# df.head(3)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [ ]:
# df = df.drop(columns=['age' , 'fever' , 'city'])

In [ ]:
# df.head(3)

gender cough has_covid
0   Male  Mild        No
1   Male  Mild       Yes
2   Male  Mild        No

In [ ]:
# from sklearn.preprocessing import OrdinalEncoder

In [ ]:
# oe = OrdinalEncoder(categories=[
#     ['Male' , 'Female'],
#     ['Mild' , 'Strong'],
#     ['Yes' , 'No']])

In [ ]:
# oe.fit_transform(df)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 0.],
       [0., 1., 1.],
       [1., 1., 0.],
       [1., 1., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 0.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 1., 1.],
       [1., 0., 0.],
       [1., 1., 0.],
       [0., 1., 1.],
       [0., 0., 0.],
       [1., 1., 0.],
       [1., 0., 0.],
       [1., 1., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [1., 1., 0.],
       [1., 0., 1.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 1.],
       [1., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [1., 0

In [ ]:
#  third - Encoding strategy - get_dummies

#  column gender(M,F) -----> gender_M(1,0) , gender_F(0,1)

In [ ]:
# df = pd.read_csv('/content/covid_toy - covid_toy.csv')
# df.head(3)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [ ]:
# df = df.dropna()

In [ ]:
# a = pd.get_dummies(df , columns=['gender' , 'cough' , 'city' , 'has_covid'])

In [56]:
# a = a.astype(int)
# a

In [ ]:
# b = pd.get_dummies(df , columns=['gender' , 'cough' , 'city' , 'has_covid'] , drop_first=True)

In [ ]:
# b = b.astype(int)
# b

In [28]:
# df = pd.read_csv('/content/tips.csv')
# df.head(2)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [29]:
# df = df.drop(columns=[ 'tip' , 'total_bill', 'size'])

In [30]:
# df.head(2)

sex smoker  day    time
0  Female     No  Sun  Dinner
1    Male     No  Sun  Dinner

In [33]:
# df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [31]:
# from sklearn.preprocessing import OrdinalEncoder


In [34]:
# oe = OrdinalEncoder(categories=[
#     ['Female' , 'Male'],
#     ['No', 'Yes'],
#     ['Sat' , 'Sun','Thur','Fri'],
#     ['Dinner' , 'Lunch'],
#     ])

In [35]:
# oe.fit_transform(df)

array([[0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],


In [50]:
# df = pd.read_csv('/content/tips.csv')
# df.head(2)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [51]:
# df =df.dropna()

In [52]:
# a = pd.get_dummies(df , columns=['sex' , 'smoker' , 'day' , 'time'])

In [53]:
# a = a.astype(int)
# a

total_bill  tip  size  sex_Female  sex_Male  smoker_No  smoker_Yes  \
0            16    1     2           1         0          1           0   
1            10    1     3           0         1          1           0   
2            21    3     3           0         1          1           0   
3            23    3     2           0         1          1           0   
4            24    3     4           1         0          1           0   
..          ...  ...   ...         ...       ...        ...         ...   
239          29    5     3           0         1          1           0   
240          27    2     2           1         0          0           1   
241          22    2     2           0         1          0           1   
242          17    1     2           0         1          1           0   
243          18    3     2           1         0          1           0   

     day_Fri  day_Sat  day_Sun  day_Thur  time_Dinner  time_Lunch  
0          0        0        1         0            1           0  
1          0        0        1         0            1           0  
2          0        0        1         0            1           0  
3          0        0        1         0            1           0  
4          0        0        1         0            1           0  
..       ...      ...      ...       ...          ...         ...  
239        0        1        0         0            1           0  
240        0        1        0         0            1           0  
241        0        1        0         0            1           0  
242        0        1        0         0            1           0  
243        0        0        0         1            1           0  

[244 rows x 13 columns]

In [54]:
# b = pd.get_dummies(df , columns=['sex' , 'smoker' , 'day' , 'time'] , drop_first=True)

In [57]:
# b = b.astype(int)
# b

In [66]:
# df = pd.read_csv('/content/insurance - insurance.csv')
# df.head(2)

age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [61]:
# df['children'].value_counts()

In [67]:
# df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [68]:
# df = df.drop(columns=['age' , 'charges' ,'bmi' , 'children'])

In [69]:
# df.head(2)

sex smoker     region
0  female    yes  southwest
1    male     no  southeast

In [70]:
# df['region'].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [64]:
# from sklearn.preprocessing import OrdinalEncoder

In [71]:
# oe = OrdinalEncoder(categories=[
    # ['female' , 'male'],
    # ['no', 'yes'],
    # ['southeast' , 'southwest' , 'northwest' , 'northeast'],
    # ])

In [72]:
# oe.fit_transform(df)

array([[0., 1., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 1., 2.]])

In [73]:
# df = pd.read_csv('/content/insurance - insurance.csv')
# df.head(2)

age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [74]:
# df = df.dropna()

In [75]:
# a = pd.get_dummies(df , columns=['sex' , 'smoker' , 'region'])

In [79]:
# a = a.astype(int)
# a

In [80]:
# b = pd.get_dummies(df , columns=['sex' , 'smoker' , 'region'] , drop_first=True)

In [82]:
# b = b.astype(int)