The Function Transformer is a tool in scikit-learn, a popular Python library for machine learing, that allowes ypu to apply a specified function to the input data. the FunctionTransformer can be useful for performing custom transformations of input data in a machine learing pipeline.


The functiontransformer takes as input a simple function that will be applied to earn sample in the data. this function can be any Python function that takes a single argument, such as a lamda function or a user-defined function. the function should return the transformed sample.

In [2]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

# create a dataset
x = np.array([[1,2],[3,4]])
# define the transformation function
log_transformer = FunctionTransformer(np.log1p)
# apply the transformation to the dataset
x_transformed = log_transformer.transform(x)
# view the transformed data
print(x_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [3]:
# 1 . custom feature Engineering

from sklearn.preprocessing import FunctionTransformer
import numpy as np

# creat a dataset
x = np.array([[1,2],[3,4]])
# define a custom feature engineering function
def squ(x):
    return np.hstack((x,x**2))
# creat a functiontransformer to apply the custom function
custom_transformer = FunctionTransformer(squ)
# apply the transformation to the input data
x_transformed = custom_transformer.transform(x)
# view the transformed data
print(x_transformed)


[[ 1  2  1  4]
 [ 3  4  9 16]]


In [8]:
x = np.array([[1,2,3,4]])
def squ(x):
    return np.hstack((x,x**2))
cumstom_transformer = FunctionTransformer(squ)
x_transformed = custom_transformer.transform(x)
print(x_transformed)

[[ 1  2  3  4  1  4  9 16]]


In [9]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

# creat a dataset
x= np.array([[1,2],[3,4]])
# define a custom scaling function
def my_scaling(x):
    return x/np.max(x)
# creat a functiontransformer to apply the custom function
custom_transformer = FunctionTransformer(my_scaling)
# apply the transformation to the input data
x_transformed = custom_transformer.transform(x)

# view the transformed data
print(x_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [11]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

# creat a dataset with missing values
x = np.array([[1,2],[3, np.nan]])
# define a custom cleaning function
def my_cleaning(x):
    x[np.isnan(x)] = 0
    return x

# creat a functiontransformer to apply the custom function
custom_transformer = FunctionTransformer(my_cleaning)
# apply the transformation to the input data
x_transformed = custom_transformer.transform(x)

# view the transformed data
print(x_transformed)

[[1. 2.]
 [3. 0.]]


In [12]:
import numpy as np
import pandas as pd


In [14]:
df = pd.read_csv('/content/placement -.csv')
df.head(3)

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1

In [15]:
x = df.drop(columns=['placed'])
y = df['placed']

In [16]:
from sklearn.preprocessing import FunctionTransformer

In [17]:
log_transformer = FunctionTransformer(np.log1p)

# apply the transformation to the dataset
x_transformed = log_transformer.transform(x)


In [18]:
x_transformed

cgpa  resume_score
0   2.212660      2.017566
1   1.969906      1.819699
2   2.226783      2.288486
3   2.064328      2.112635
4   2.142416      2.116256
..       ...           ...
95  1.991976      1.998774
96  2.222459      2.170196
97  2.034706      2.172476
98  2.212660      1.891605
99  1.958685      2.029463

[100 rows x 2 columns]

In [19]:
df = pd.read_csv('/content/covid_toy - covid_toy.csv')
df.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [23]:
x = df['age']+5
x.head(3)

0    65
1    32
2    47
Name: age, dtype: int64